In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Adding a new column

### assign()

When to use assign?

* Add multiple columns in a single line of code
* When you need to overwrite the values of an existing columns (best practice)

It returns a new object (a copy) with all the original columns in addition to the new ones

In [3]:
import numpy as np

In [4]:
# create random numbers for our new score columns
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [5]:
# create a series using the random numbers (because we need add an index)
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [9]:
# they are dataframe
series1

0      36
1      20
2      69
3      43
4      74
       ..
995     7
996    40
997    69
998     7
999     9
Length: 1000, dtype: int32

In [15]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,36,96
1,female,group C,some college,standard,completed,69,90,88,20,94
2,female,group B,master's degree,standard,none,90,95,93,69,83
3,male,group A,associate's degree,free/reduced,none,47,57,44,43,4
4,male,group C,some college,standard,none,76,78,75,74,68
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,7,58
996,male,group C,high school,free/reduced,none,62,55,55,40,54
997,female,group C,high school,free/reduced,completed,59,71,65,69,36
998,female,group D,some college,standard,completed,68,78,77,7,8
999,female,group D,some college,free/reduced,none,77,86,86,9,66

In [19]:
# using assign() to add multiple columns
df_exams = df_exams.assign(score1=series1, score2=series2)
# overwrite the values because we only got a copy

In [20]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,36,group B,bachelor's degree,standard,none,72,72,74,36,96
1,female,20,group C,some college,standard,completed,69,90,88,20,94
2,female,69,group B,master's degree,standard,none,90,95,93,69,83
3,male,43,group A,associate's degree,free/reduced,none,47,57,44,43,4
4,male,74,group C,some college,standard,none,76,78,75,74,68
...,...,...,...,...,...,...,...,...,...,...,...
995,female,7,group E,master's degree,standard,completed,88,99,95,7,58
996,male,40,group C,high school,free/reduced,none,62,55,55,40,54
997,female,69,group C,high school,free/reduced,completed,59,71,65,69,36
998,female,7,group D,some college,standard,completed,68,78,77,7,8
999,female,9,group D,some college,free/reduced,none,77,86,86,9,66

### insert()
Inserts a new column at a specific position or index.

In [21]:
# using insert() to add a column at a specific position
df_exams.insert(1, 'test', series1)
# first arg -> introduce the index of the new column(adding it at index number 1)
# second arg -> name of the column 
# third arg -> the value

ValueError: cannot insert test, already exists

the error is becuase it been run twice

In [23]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,36,group B,bachelor's degree,standard,none,72,72,74,36,96
1,female,20,group C,some college,standard,completed,69,90,88,20,94
2,female,69,group B,master's degree,standard,none,90,95,93,69,83
3,male,43,group A,associate's degree,free/reduced,none,47,57,44,43,4
4,male,74,group C,some college,standard,none,76,78,75,74,68
...,...,...,...,...,...,...,...,...,...,...,...
995,female,7,group E,master's degree,standard,completed,88,99,95,7,58
996,male,40,group C,high school,free/reduced,none,62,55,55,40,54
997,female,69,group C,high school,free/reduced,completed,59,71,65,69,36
998,female,7,group D,some college,standard,completed,68,78,77,7,8
999,female,9,group D,some college,free/reduced,none,77,86,86,9,66