In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Adding a new column

### Adding a new column with a scalar value

In [3]:
# adding new column to dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

# Adding a new column with an array
The dataframe has 1000 rows, so we need to create an array with 1000 elements

In [4]:
# import numpy
import numpy as np

In [6]:
# create an array of 1000 elements
language_score = np.arange(0, 1000) # gives us range that starts with first argument and to the last argument

In [7]:
language_score

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [12]:
# verify the length of the array because length of the array must be the same as the length of the dataframe
len(language_score)

1000

In [13]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [20]:
# create random integer numbers between 1 and 100 (method-> random.randint)
int_language_score = np.random.randint(1, 100, size=1000) 
# first arg -> lowest value of the random numbers (inclusive)
# second arg -> the highest value in the random numbers (exclusive)
# third arg -> is the size 

int_language_score

array([60,  9, 67, 22, 40, 92, 69, 67, 55,  6,  8,  6, 27, 44, 66, 34, 95,
       40,  4,  7, 15, 44, 86, 49, 26, 48,  5,  8, 47, 12, 47, 95, 64, 38,
       83, 19, 73, 22, 82, 25, 56,  9, 23, 68, 84, 22, 69, 47,  9, 91,  2,
       28, 40, 52, 21, 39, 90, 39, 83,  8, 91, 13, 26, 88, 99, 65, 26, 22,
       72, 95, 79, 38, 51, 25, 78, 75, 81, 66, 91, 90, 29, 40, 20, 61, 10,
       55, 39, 65, 84, 50, 95, 93, 59, 91, 32, 82, 27, 30, 36, 73, 76, 59,
        6, 26,  2, 35, 76, 72, 39, 55, 40, 33, 90, 77, 22, 85, 77, 64, 60,
       57, 88, 66, 35,  3, 48, 16, 55, 58, 27, 78, 82, 39, 97, 30, 82, 56,
        4, 79, 70, 42,  5, 22, 57, 46, 80, 89, 84, 34, 20, 57, 86, 42, 57,
       90, 11, 21,  6, 24, 51, 51,  3, 22, 13,  6, 96, 59, 97, 38, 61, 31,
       73, 36, 55, 51, 62, 95, 45, 57,  6, 28, 56, 93, 10, 14,  5, 80, 94,
        3, 64, 36, 16, 54, 90, 69, 49, 37, 98, 15, 80, 98, 21, 91, 87, 77,
       68, 91, 19, 25, 25, 94, 39, 30, 18, 52, 56, 67, 73, 66, 15, 71, 74,
       15, 30, 69, 43, 86, 53, 33, 11, 85, 70,  9, 87, 66, 85, 50, 49, 20,
       55, 72, 83, 23, 69, 37, 26, 43, 45, 26, 96, 94, 82, 51, 87, 53, 55,
       82, 98, 75, 59,  1, 91,  4, 60, 25, 28, 97,  6, 50, 36, 17, 78, 36,
       34, 35,  4,  3,  9, 13, 63, 92, 35, 65, 88, 43, 24, 79, 70,  5, 21,
       29, 83, 43, 75, 51, 86, 74, 45, 39, 71, 17, 26, 36, 54, 24, 49, 86,
       34, 30, 97, 95, 50, 16, 66, 11, 50, 86, 30, 67, 56, 97, 35, 27, 70,
       14, 68, 93, 69, 16, 49, 12, 60,  6, 35, 72, 71, 88, 10, 22, 69, 96,
       43,  4, 47, 23, 11, 96, 24, 83, 19, 94, 69, 85, 78, 81, 22, 78, 73,
        9, 54, 19, 40, 83, 60, 53, 37, 76, 77, 27,  4, 92, 91, 22, 20, 69,
       14, 72, 23, 34, 24, 49, 43, 84, 52, 52, 19, 64, 70, 97, 67, 71,  5,
       40, 68,  8, 73,  9, 21, 58, 91, 19, 67, 19, 80, 11, 72, 10, 78, 97,
       88, 72, 49, 49, 27, 21,  7, 20, 72,  6, 63, 96,  2, 56, 66, 48, 20,
       29, 12,  4, 59, 20, 33, 21, 87, 35, 28,  4, 27, 34, 65, 85, 63, 68,
       19, 54, 54,  4, 48, 31, 17, 24, 32, 19, 58, 16, 54, 99, 25, 51, 19,
       57, 28, 39, 98, 42, 68, 25, 74, 74, 38,  5,  9, 30,  7,  1, 30, 97,
       63, 38, 43, 64, 99, 73, 16, 70, 12, 91, 97, 65, 67, 85, 24, 71, 36,
       87, 53, 31, 46, 25, 12, 38, 75, 30, 85, 54, 15, 83, 38, 87, 92, 56,
       21, 62, 55, 19, 41, 93, 28, 60, 47, 71, 74, 41, 47, 28, 99, 75, 92,
       60, 30, 99, 76, 75, 48, 69, 93, 90, 98, 28, 97, 35, 90, 34, 60, 35,
       61, 43, 55, 25, 55, 97, 78, 29, 22, 43, 63, 32, 13, 62, 20, 28, 84,
       34,  6, 15, 88, 59, 88, 81, 56, 64, 56, 10, 69, 19, 33, 76, 51, 46,
       93, 14, 73, 11, 10, 68, 47, 77, 60, 38, 18, 36, 47, 10, 34, 32, 67,
       21, 56, 87, 98, 84, 63, 33, 49,  9, 79, 68, 56, 71, 84, 38, 33, 78,
       86, 63,  2, 62, 36, 88, 16, 67, 29,  8, 90, 80, 70, 32, 35, 99, 79,
       15, 68, 12, 69, 21, 93, 68, 14, 32, 95, 35, 49, 30, 42, 79, 86, 48,
       16, 19, 94, 77, 65, 68, 54, 99,  7, 73, 46, 49, 39, 44, 87,  8, 28,
       60, 44, 20, 16, 97,  6, 94, 21,  6, 29, 51, 94, 87, 97, 62,  1, 91,
       99,  8, 27, 85, 39, 72,  7, 97, 81, 89,  3,  8, 56, 75, 11, 74, 56,
       87, 90, 44, 38,  8, 98, 51, 83, 50, 46, 29, 39, 22, 56, 66, 83,  1,
       16, 91, 54, 13, 93, 79, 25, 84, 13, 62, 43,  4, 76, 90, 80, 55, 45,
       79, 79, 43, 10, 35,  1, 92, 86, 11, 74,  3,  5, 78, 94, 23, 94, 92,
       99, 92, 18, 30, 24, 97, 70, 96, 14, 72, 80, 62, 16, 87, 76, 24, 86,
       23, 54, 90, 14, 30, 31, 65, 78, 42, 60, 52, 50, 65, 42, 24, 16, 29,
       22, 57, 18, 43, 72, 46,  9, 73, 25, 43, 68, 81, 57, 66, 54, 49, 45,
       96, 49, 90, 74, 66, 87, 70, 59, 35, 87, 69, 56, 66, 38, 94, 96, 95,
       20, 81, 68, 46, 57, 75, 20, 63, 62, 45, 73, 78, 36, 59, 40,  6, 40,
       61, 58, 39, 13, 94, 59, 96, 88, 56, 25, 37, 26, 83,  9, 87, 19, 36,
       91, 51, 47, 49, 59, 85, 24, 51, 90, 99, 40, 91, 46, 75, 90, 79, 57,
       39, 23, 35, 67, 70,  1, 49, 57, 73, 78, 24, 50, 75, 17, 98, 20, 15,
       64, 25, 35, 87, 59, 52,  6,  2, 37, 56, 66, 85, 66, 90, 21, 47, 95,
       48, 79, 95, 33, 22, 98, 96,  1, 52, 61, 34, 24, 25, 42,  6, 56, 96,
       59, 57, 16, 41, 91, 31, 87,  4,  1, 87, 48,  4, 81, 52, 16, 46, 67,
       31, 44, 42, 88, 36, 93, 99, 33, 40, 69, 11, 57, 61, 49, 54, 72, 94,
        3, 27, 12, 77, 48, 82, 11, 18, 78, 79,  4, 60, 57, 76, 10, 78, 58,
       16, 98,  4, 98, 98, 54, 70, 78, 53,  5, 55, 26, 28, 24, 90, 26, 83,
       11, 19, 14, 74, 95,  3, 53, 21, 36, 59, 38, 12, 39,  4],
      dtype=int32)

In [21]:
print(len(int_language_score))

# min value inclusive and high value exclusive
print(min(int_language_score))
print(max(int_language_score))

1000
1
99

In [22]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,60
1,female,group C,some college,standard,completed,69,90,88,9
2,female,group B,master's degree,standard,none,90,95,93,67
3,male,group A,associate's degree,free/reduced,none,47,57,44,22
4,male,group C,some college,standard,none,76,78,75,40
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,59
996,male,group C,high school,free/reduced,none,62,55,55,38
997,female,group C,high school,free/reduced,completed,59,71,65,12
998,female,group D,some college,standard,completed,68,78,77,39
999,female,group D,some college,free/reduced,none,77,86,86,4

In [23]:
# create random float numbers between 1 and 100
np.random.uniform(1, 100, size=1000)

array([75.02969507, 65.02041467, 77.64689712, 55.5512666 , 56.69526816,
       52.6616912 , 10.07008545, 73.58813758, 92.88591364, 52.40253144,
       44.84316531, 99.62374084, 23.29977406, 84.62927136, 51.49183491,
       38.90427021, 85.33363241, 41.24977744, 51.16228419, 77.90900605,
       10.47039637, 37.60197071, 29.85475668, 85.63451255, 48.64717645,
       44.0839029 , 52.2597308 , 65.55008138, 82.27899321, 26.05148534,
       93.90670293, 24.10180065, 95.77899938, 82.20067552, 52.3501337 ,
       35.67460026, 21.64596064, 69.74739136, 85.81544739, 15.11584465,
       86.50869075, 94.72429047, 38.61570071, 46.44750537, 13.75878083,
       51.23804187, 55.09966028, 18.23995051, 19.84711845, 60.61286977,
       59.57656865, 60.74221868, 31.21012462, 99.83065781, 73.0626717 ,
       66.86767624, 47.58553998, 32.52821429, 57.01603646, 58.50258444,
       15.61317173, 23.89511783, 10.20313484, 61.90420983, 33.19807827,
       14.11863196, 41.90136863, 46.93549452, 65.58929539, 23.73121682,
       88.44732604, 77.9741892 , 18.87724709, 12.91804372, 22.49832716,
       70.82830494, 93.53143327, 68.9431069 , 60.25760481, 21.26971614,
        7.43369601, 66.29458753, 87.38726424,  5.19313584, 56.5179254 ,
       14.19540695, 40.20922082, 97.01625634, 59.85989142, 72.08241751,
       81.40650643, 69.90893215, 41.12393613, 81.01560816, 67.97742575,
       12.10325107, 11.02099071, 87.44847807, 23.46079615, 52.04196298,
       99.20725585, 34.21469649, 58.91132704, 50.27741451, 24.07085009,
       19.6618913 , 99.30564095, 38.52026215, 60.42050019, 97.1676016 ,
       95.04669422, 53.28043774, 27.23430023, 28.38583922, 95.1179846 ,
       74.89972433, 69.07123791, 31.41786749,  4.55807615, 52.39422717,
       84.1554642 , 22.39841   , 49.76266576, 87.97046271, 24.54697432,
       59.46178105,  7.0041777 , 12.50393333, 49.81930121, 30.74224886,
       17.37406369, 87.19342054, 66.22632983, 53.55317704, 24.68135968,
       71.37992461, 45.29513542,  9.93814243, 11.0113959 , 62.14927867,
       43.13562117, 63.00444289, 62.69287163, 67.79610568, 26.502352  ,
       25.50027466, 93.24747065, 74.07095698, 50.94047665, 22.36827076,
       95.66219211,  2.15529949, 68.86751265, 66.23899563, 73.7729513 ,
       57.52123835, 71.21616636, 33.29008152, 67.10825458,  3.87437673,
       34.205996  ,  8.7357791 , 38.84609666, 91.62009793, 60.91182821,
       55.59297458, 14.09901548,  1.25142332, 37.24140618, 27.14845315,
       87.34839643, 70.23474587, 15.9841193 , 66.8818673 , 98.10728404,
       10.72780923, 84.9257831 , 47.4934627 , 60.00115072, 16.24999291,
       29.95787628, 33.03048629, 35.42735841, 66.7466122 , 33.94502327,
       51.76052293, 80.96978568, 19.90979264, 84.60153438, 75.2097128 ,
       60.74233931, 70.82456456, 35.92271434, 29.1392712 , 68.20479172,
       39.74437556, 96.61514736, 35.58122104, 50.20398093,  7.29405404,
       11.23920568, 16.84754755, 50.1020511 , 87.76206864, 24.55853045,
       77.74107635, 55.6436212 , 82.47582326, 49.46123088, 97.13436458,
       60.79760062, 67.79575173, 65.23878067, 68.01057532, 72.37073086,
       99.0109119 , 24.22182952, 63.29718144,  4.43613025, 29.06891696,
       65.07531181, 23.46887758, 35.93352336, 54.25569859, 76.18863622,
       83.33106908, 25.12010108, 61.0696308 , 69.43829501, 98.82048539,
       45.71523862, 37.10260591, 93.6484877 , 50.05972561, 96.50005147,
       61.99613027, 28.27985136, 91.58364394, 42.25104565, 95.84901061,
       49.18091725, 19.84508278, 97.81815103,  6.96667726, 67.4348046 ,
        6.85310201, 67.57812506,  7.9220104 , 33.45662856, 70.35987253,
       82.39353367,  3.68978781, 69.03789865, 80.90683856, 69.10971125,
       71.89709333, 82.64300004,  6.83553094, 74.2761699 , 76.80123367,
       54.55292451, 37.39371091, 67.11036332, 84.72796391, 57.5990795 ,
       77.0524586 , 42.78372721, 18.72842709, 64.911249  , 62.78964178,
        5.62725219, 26.96856665, 39.13217689,  2.18919775, 26.08016501,
       63.8676656 , 64.97264662, 81.08729585, 48.48532279, 86.12116042,
       56.59497469, 29.4531406 , 38.7160066 , 30.22827585, 81.29264771,
       49.30397618, 21.81830203, 92.07779785, 23.82384656, 11.75799842,
       22.1637244 , 41.34840016, 55.6314111 , 73.99777154, 69.52052769,
       55.74815542, 74.80336039, 25.54919602, 12.01673163,  2.90246137,
       78.8686765 , 43.59433486, 71.42393915,  7.47036318, 83.38064917,
       62.30822556, 86.95255183, 10.22844103, 45.34026678, 87.17077352,
       62.57427207, 76.33529866, 42.91411184, 50.54826229, 50.28554973,
       41.04778644, 51.97710931, 40.90237874, 65.58204214, 30.16740482,
       86.30194262, 13.04481846, 59.80964198, 11.51677603, 12.25597176,
       88.9292856 , 20.25547694, 94.91193946, 61.7075175 , 85.18908891,
       87.08898282, 47.8478166 , 36.39945562, 51.97186603, 24.71613394,
       95.48893416, 94.96507267, 42.51733707, 57.18585605, 94.67246297,
       45.16405689, 56.64152131, 18.5526724 , 69.72723834, 49.27461291,
       94.32088818,  7.46984439, 42.51552016, 21.17882976, 84.68667069,
       48.49389784,  5.47126816, 92.36104375, 33.2254409 , 51.1348349 ,
       32.47906838, 87.00434916, 11.74829266, 54.61556883, 68.9465234 ,
        1.08373045, 91.68631504, 62.71401528, 19.00583232,  2.30368035,
       88.80572595, 77.55259992, 77.82183289, 54.09315222,  6.60901058,
       11.89361478, 51.15262602, 42.23578244, 44.69181669, 39.06780961,
       24.66847349, 65.43228376, 34.86968003, 41.11130265, 69.86166766,
        1.3034669 , 10.47789931, 60.55871158, 59.77436977, 12.86601805,
       99.13020721,  3.18381529, 38.52345749, 17.34467603, 28.11032017,
       31.24110875, 16.77865584, 58.8918518 , 10.97736592, 98.7505698 ,
       27.84219488, 90.87255311, 79.13909612,  3.29214825, 84.36252149,
       50.3303069 , 57.618804  , 23.5050144 , 20.65346472, 72.87373221,
       73.2918295 , 56.35564096, 52.02907773, 36.62059788, 75.14525084,
       62.69409732, 75.68147188, 51.8583904 , 22.34701792, 11.42712218,
       43.02522571, 70.07311333, 77.10607536, 33.36480638, 45.32986459,
       72.12933207, 55.99262287, 41.43157846, 69.27065597, 57.80572679,
       63.282306  ,  3.05691891, 38.435519  , 28.16248966, 45.51445766,
       14.23023933, 67.01983028, 34.46040156, 43.55424136,  3.32817009,
       58.77124101, 79.3839598 , 31.27421897, 88.56496349, 91.41897007,
       36.38444413, 73.03925427,  5.61379526, 89.0815071 , 79.72935916,
       98.48270642, 13.29335791, 82.40973603, 72.80637946, 50.15188927,
       19.27190492, 71.6777463 , 81.32119995, 38.02523288, 31.72105886,
       55.27894778, 43.89970736, 56.63951964, 17.84696965,  6.0173282 ,
       48.12663356, 49.78137355, 16.13955702, 82.45890909, 31.37484709,
       18.30328145, 28.22324066, 96.22837494, 80.98430099,  1.33811896,
       37.89706552, 25.48013177, 62.56788839, 31.50414323, 68.37919423,
       20.35118702, 39.22086404, 25.26401254, 55.08058174, 23.82346385,
       35.92002045,  6.4259352 , 29.97851735, 26.04804168, 21.21132389,
       46.32694543, 23.70531883, 15.15707568, 55.47692921, 17.30733823,
       25.66750698, 27.9517689 , 14.53826377, 61.08791505, 89.58012861,
       14.50064484, 40.10162546, 24.58522187, 98.81713116, 10.66155693,
       16.01119853, 88.94734784, 71.91107427, 93.43415634, 89.60971496,
       21.90506695, 80.54680534, 94.36821762, 25.00796685, 59.61852015,
       32.75739941, 32.89887524, 36.70040578, 49.2830758 , 43.54787407,
        6.9471216 , 25.79394471, 28.00133897, 32.13010311, 47.77438898,
       35.25474583, 88.49380254, 19.45135631, 46.79868388, 50.4505341 ,
       95.81861393, 65.36733623, 94.7513104 , 71.67452993, 10.6687409 ,
       91.85851792, 90.06222947, 64.92502697, 45.00062997, 13.97492121,
       33.84932815, 93.67026384, 63.40647972, 29.96649641, 45.62370208,
       40.52587323, 24.90851495, 28.25677567,  9.94942928, 52.26251396,
       77.52354515, 73.47624607, 56.95002677, 21.36455835, 82.05850264,
       12.34666128, 84.874901  , 88.18550054, 82.58476952, 85.60887386,
       70.31765581, 16.05763268, 24.17294992, 15.59194879, 13.06978027,
       63.48192236, 59.83296148, 23.01031126, 76.00352151, 55.75088682,
       34.85544909,  7.70052742,  6.62891428, 73.3936233 , 40.72930268,
       64.65098912, 22.11223852, 25.19206639, 48.4059736 ,  3.93213423,
       34.58871866, 32.81470372, 67.19325976, 59.33005562,  3.93956307,
       24.78970409, 19.2378657 ,  5.3805993 , 33.35755266, 77.23472661,
       98.72329544, 94.12846392, 47.12140534, 92.35990907, 80.94707044,
       78.45757629, 86.09735257, 10.44577346, 38.10400737, 70.61770596,
       69.23841409, 79.92679013, 70.58690234, 37.46845074, 16.30390818,
       28.82330271,  7.74199097, 31.35039833, 10.36910214, 70.5446507 ,
       49.30025175, 82.40423324, 43.91897023, 28.2075605 , 77.70968684,
       53.02157724, 35.88728191, 34.38256864, 95.28009804,  7.53039021,
       53.23245914, 78.71142436, 25.31955258, 92.05156247, 26.33804725,
       97.68271237, 54.58184654,  7.70040008, 56.49268867, 55.03193219,
       78.47005775, 95.3997524 , 60.66841524, 66.20725515, 99.56262192,
       11.86102548, 95.92900737, 93.78378509, 97.37077225, 49.08604078,
       94.08346527, 52.14856432, 37.60825536, 74.94841884, 34.17527834,
       13.06138994, 35.5585722 , 70.49213591, 76.82687719, 16.89468051,
       97.88019945, 95.02303823, 74.72046537, 54.709922  , 75.48850719,
       83.55151129, 62.97914447, 52.5337726 , 39.68238773, 34.38577872,
       64.34906018, 19.94715297, 11.75490939, 56.39241048, 21.96859436,
       36.37613483, 87.2681888 , 28.90201407, 15.81420744, 25.99964706,
       70.41375244, 61.89916496, 91.26066974, 42.39192256, 69.02389386,
        9.7307484 , 63.20280084, 99.45715128, 21.97549505, 66.39787119,
       46.38349612, 15.87731705, 64.16556323, 60.65496431, 34.4878684 ,
       37.57688639, 91.67809651, 84.14521839, 39.24641101, 87.78124217,
       42.17384485, 38.38974442, 47.32909231, 23.22843213, 28.06451811,
       24.70767444, 25.9048224 , 29.33511716, 39.7628479 , 98.90228857,
       72.99346457, 89.40455989, 34.46258069, 31.74357434,  6.18392639,
       59.55296601, 42.37720507, 68.97930792, 60.17589562, 34.63955827,
       76.8198722 , 81.3074024 ,  6.26967775,  6.45682388, 37.81588237,
       26.83835239, 60.59255072, 23.60047958, 21.74783952, 35.45141559,
       56.66028889, 72.78993733, 56.98719455, 79.91171281, 21.31441961,
        7.95843755, 92.37136588, 61.66494558, 19.81313248, 83.13100935,
       48.01134221, 54.05165286, 20.50406977, 44.97772812, 84.6538335 ,
       27.54273304, 29.75615213, 22.96927286, 57.59006326, 72.57043522,
        9.22816369, 38.35810863, 46.55291766, 62.12731974, 32.93264867,
       77.14973981, 55.77161792, 60.56572745, 36.40142894,  4.62249876,
       37.82641144, 66.23346572, 63.1155621 , 89.98729976, 26.59185345,
       28.7626436 , 13.74173032, 20.99649505, 40.50437531, 63.66867148,
       71.86503625, 60.32942055, 21.86862952, 96.37257701, 61.20623918,
       47.2656872 , 72.18097558, 97.1223329 , 43.66795159, 47.36474634,
        9.44229769,  9.31036106, 85.37143977, 34.78436369, 23.62237268,
       16.40203298, 43.71616975, 71.4093835 , 26.49236144, 62.28794689,
       77.66651938, 62.32948398, 29.47384692, 33.38223447,  6.78388325,
       52.86108713, 14.31534256, 19.9479344 , 64.44275851, 24.46471003,
       25.3551512 , 85.7155706 , 34.05184175, 91.56310194, 24.33641444,
       70.02779025, 39.29090849, 24.71366189, 42.39805813, 39.24353671,
       29.42715195, 50.34429364, 60.77635716, 29.29746877, 29.04944319,
       33.87093266,  2.63596059, 91.0083931 , 19.31365068, 70.64999514,
       71.2620751 , 34.74653383, 49.34160428, 90.23193507, 40.22298257,
       75.29774492, 45.85950793, 73.66318324, 65.46453277, 58.60378229,
       10.75985821, 51.24584815,  3.32096792, 73.50915179, 10.90268667,
       53.27784823, 90.27782382, 26.88844629, 33.93886776, 94.01257602,
        1.4093895 , 55.74588502, 46.49371017, 99.25924208, 58.40335026,
       63.07759616, 41.18188503, 58.14586244, 98.42038631, 98.80774387,
       36.50587452, 63.90816225, 90.36502941,  2.96790857, 66.86325512,
       52.51188705, 50.76433626, 90.70224499, 71.36374006, 86.92526827,
       80.84131254,  8.83604194, 96.61207952, 22.59825563, 76.3187429 ,
       27.26488629, 23.44902462, 78.78636974, 16.18850247, 34.91065909,
        8.52753994, 67.82502974, 57.20848505, 47.40839553, 99.61981338,
       70.79894167, 12.07266211, 64.33364737, 74.35256523, 51.03645406,
       60.62331309, 18.95933411, 74.43743212, 62.92419411, 95.66895183,
       43.50679084, 13.90916617, 64.09823921, 55.41615343, 42.24887362,
       51.71497865, 44.09110253, 45.10650864, 53.24318494, 75.64403993,
       44.3822394 , 65.69697817, 63.36211971, 38.15234245, 44.92690907,
       62.35319441, 69.34151569, 12.25381587, 35.75164598, 83.43153637,
       66.6646634 , 80.15435011, 86.38372965, 81.7876164 , 29.38376596,
       69.85002946, 14.63113096, 83.9463649 , 69.05939817, 51.49599478,
       87.9527964 , 84.08957876, 25.33189992, 83.4488823 , 47.19587186,
        9.74962639, 52.65459331, 76.99858164, 85.55698676, 80.15495957,
       96.84440422, 73.65894949,  6.39057661, 28.8376574 , 39.51228645,
       43.81230316, 57.24317993, 32.03799637, 13.91527645, 92.21237482,
       59.85491446, 39.13798724, 82.83214533,  1.55623972, 46.66176015,
       97.97782359, 49.39531727, 15.90762698, 37.24001876, 47.51196266,
       55.69492104, 45.81400123, 22.02984573, 92.02506346, 91.11945379,
       69.44572513, 50.01006751, 55.89752403,  6.85633432,  5.90823832,
       12.57105312,  6.47519138, 88.13736826,  5.21667251,  2.70443716,
       34.33105441, 24.05325214, 51.88961244, 63.85836814, 29.88075558,
        4.04391337, 97.04084125, 25.79844343, 24.41681481, 11.78473003,
       40.3369043 , 18.38652328, 14.57996656, 74.83632642, 80.93443843,
       57.17582758, 66.63622717, 59.77751674,  5.57828019,  3.33460253,
       38.87889401, 40.70031194, 36.7730038 , 86.70578995, 51.35335641,
       77.09137415, 77.55870747, 49.32913921, 11.6288676 , 34.88566433,
       56.47344461, 83.34139281, 16.42726147, 83.74728216, 19.42287531,
       15.17504686, 49.57452917, 56.09299541,  3.83773273, 96.95095137,
       99.22724493, 34.7415051 , 85.1481106 , 85.79559739, 14.67319505,
       35.78466153, 17.2263232 , 45.06208247, 72.3233795 , 53.75720732,
        3.17729184, 15.4317627 , 68.84985461, 61.39850795, 90.84148596])