In [1]:
import pandas as pd

In [2]:
# reading and showing dataframe
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Create Index

In [3]:
import numpy as np
import random

In [4]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [5]:
# shuffling the indexes using random library
random.shuffle(new_index)
new_index

array([687,   5, 172, 812,  71, 100, 817, 390, 165, 600, 514, 807, 641,
       748, 810, 114, 387, 351, 303, 826, 582,  26, 380, 798, 195, 794,
       825, 421, 330, 971, 728, 802, 402, 763, 771, 609, 626, 265, 460,
       606, 216, 408, 425, 344, 968, 590, 296, 683, 978, 331, 252,  54,
       793, 819, 599, 680, 619, 841, 765, 176, 799, 116, 105, 485, 697,
       410, 343, 319, 870, 983,  88, 815, 924, 290, 426, 544, 125, 266,
        37, 438, 311, 618, 442,  22, 811, 883, 718, 414, 392, 452, 585,
       664, 164, 444, 433, 977, 182,  38, 441,  78, 446,  43, 238, 820,
       617, 334, 482, 218, 778, 596, 123, 575, 534, 639, 222, 318, 403,
       272, 282, 527,   9, 376, 753, 204,  91, 634, 814, 120, 719, 692,
       171, 427, 625,  81, 886, 861,  74, 226, 911, 931, 509, 633, 738,
       298, 121, 725, 821, 333, 953, 677, 889, 407, 467, 836, 399, 359,
       383, 863, 136, 418,  82, 500, 835, 764, 974, 498, 217, 855, 707,
       992, 149, 908, 206, 439, 791, 943, 730,  77,   2, 624, 645, 239,
       483, 259, 628, 513, 552,  40, 774, 716, 154, 436, 128,  34, 525,
        25, 951, 249, 785, 457, 640, 476, 358, 453, 495, 270, 199, 573,
       454, 997, 415,  28, 868, 651, 955, 322, 759,  55, 611, 335, 443,
        41, 665, 374, 648, 422, 474, 907, 481, 790, 131, 947, 744,  32,
       676, 192,  14,  87, 612, 508, 553, 268, 196, 695, 115,  69, 180,
       521, 581, 285, 750, 961, 986, 973, 260, 905, 181, 280, 837, 293,
       464,  98, 391, 555, 662, 884,  21, 652,  35, 583, 432, 504, 231,
       742, 577, 957, 657, 900, 800, 506, 428, 733, 529,  66, 604,  27,
       304, 234,  68, 890, 475, 593, 646, 613, 306, 357, 104, 413, 887,
       537, 256, 486, 126, 745,  60, 314, 254, 368, 936, 580, 777, 488,
       704, 352,  63, 779, 674, 364, 755, 127, 277, 109, 743, 519, 559,
       299, 845, 219, 174, 684, 880, 235, 864,  96, 989, 493, 220, 717,
       693, 241, 954, 451, 188, 949, 166, 353, 455, 472, 295, 533, 461,
       462,  79, 354, 975, 523, 754, 210, 248, 246, 678, 338, 267, 332,
       491, 283,  83, 938, 848, 653, 809, 389, 901, 156, 903, 469, 406,
       772, 671, 134, 679, 865, 723, 132, 859, 284, 409,  99, 944, 852,
       437, 655, 294, 780, 214, 970, 909, 388, 984, 667, 145, 966, 578,
        19, 847, 597, 189, 875, 379,  44, 930, 602, 229, 326, 197, 373,
       404, 487, 916, 620,  50, 644, 117, 151, 833, 207, 976, 834, 557,
        64, 571, 591, 681, 405, 709,  76, 856,  73, 808, 842, 385, 594,
       168, 524, 297, 193, 211,  53, 783, 689, 832, 112, 969, 542, 795,
       649,  24, 370, 287, 721, 929,  46, 237, 215, 700, 150, 854, 878,
       355, 369, 840, 232, 307,  31, 202,  33, 394, 939,  93,  94, 431,
       729, 106, 339, 952, 879, 223, 201, 891, 367, 572, 567, 830, 278,
       654, 926, 699, 247, 686, 348, 566, 111, 827, 610, 925, 958, 288,
       325, 384, 701, 419, 503, 965, 301, 713, 751, 991, 658, 375, 710,
       139, 434, 342, 595, 928, 492, 140, 588, 586, 263, 101, 881, 178,
       828, 108, 490, 213, 979, 221, 562, 371, 673, 558, 789, 531, 806,
       560, 184, 345, 142, 669,   8,  29, 160, 208, 228, 851,  58, 479,
       516, 458, 760,   0, 119, 627, 262, 948, 773, 520, 731, 133, 843,
       706, 614, 736, 264, 540, 722, 372, 967,  84, 569, 703, 548, 396,
       480, 561, 696, 107, 838, 638,  65, 720, 161, 853, 757, 393, 636,
       829, 994, 535, 365,  30, 313, 308, 337, 416, 622, 914, 776, 766,
       309, 752,  42, 601, 623, 672, 532,  45, 225, 660, 568, 329, 656,
       146, 361, 898, 702, 300, 450, 177, 962, 227, 882, 980, 615, 381,
       302, 340, 274, 869, 517, 275, 305, 739, 935, 281, 423, 781, 183,
        10, 499,   1, 512, 637, 253, 727, 927, 631, 255, 449,  70, 478,
       917, 945, 993, 642, 191, 251, 987,  92, 714,  36, 932, 746, 363,
       603, 670, 872, 592, 668, 547, 740, 587, 395, 148, 910, 157, 502,
       471, 477, 964, 243, 803, 429, 489, 770,  72, 893, 767, 245,  95,
       137, 694,  90, 187, 981, 923, 574, 756, 956, 816, 643,  97, 549,
       605, 675, 401, 551, 273, 990, 666, 179, 411, 946,   6, 261, 118,
        56, 712,  47, 885, 224, 607, 959, 169, 530, 130, 876,  23, 163,
       762, 129, 635, 417, 440, 205, 934, 186, 113, 920, 937, 316, 769,
       312, 158, 496, 902, 200, 650,  61, 143, 323, 786, 398, 608,  12,
        48, 906, 871,  57, 873, 813, 190, 899, 598, 999, 110, 922, 915,
       465, 321, 888, 315, 589, 522, 839, 459, 230, 292,  13, 659, 397,
       690,   7, 630, 466, 563, 846, 831, 528, 447, 963, 327, 538, 942,
       554, 198, 663,  20, 484, 904, 147, 497, 382,  52,  86, 212, 546,
       170, 545, 155, 866, 797, 511, 144, 356, 276, 347, 430,  62, 822,
       412,  85, 823, 734, 804, 726, 279, 735, 470, 257, 258, 895,  59,
       874, 996,  39, 616, 244,  67, 724, 998, 378, 507, 377, 175, 844,
       576, 445, 661, 941, 933, 850, 741, 185, 877, 921, 579, 892, 621,
       715, 768, 919, 386, 526, 758, 240,   3, 135, 801,  17, 194,  15,
       737, 289, 494, 912,   4, 691, 632,  89, 138,  80, 269, 960, 858,
       867, 860, 913, 894, 556, 366, 805, 124, 688, 162, 629, 400, 236,
       456, 896, 103, 286, 565,  51, 536, 468, 698, 424, 505, 346, 708,
       350,  75, 167, 448, 102, 711, 250, 473, 818, 463, 539, 122, 349,
       173, 543, 541,  16, 310, 341, 824, 328, 501, 360, 732, 291, 153,
       972, 761, 336, 950, 320, 570, 775, 510,  18, 782, 550, 647, 682,
       747, 233, 784, 209, 788, 317, 705, 515, 849, 857, 271, 982, 203,
       749, 796, 159, 141, 792, 940, 985, 362, 584, 862, 324, 242, 420,
       988,  11, 918, 152, 435, 518, 897, 685, 564, 995,  49, 787])

# create a new column with new index (set new_index variable to a new column of the orginal dataframe)
df_exams['new_index'] = new_index
df_exams

# Set Index

In [7]:
# set new_index column as of the dataframe by the method (set_index)
df_exams.set_index('new_index', inplace=True) #used inplace because the index method only creates a copy
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
687,female,group B,bachelor's degree,standard,none,72,72,74
5,female,group C,some college,standard,completed,69,90,88
172,female,group B,master's degree,standard,none,90,95,93
812,male,group A,associate's degree,free/reduced,none,47,57,44
71,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
685,female,group E,master's degree,standard,completed,88,99,95
564,male,group C,high school,free/reduced,none,62,55,55
995,female,group C,high school,free/reduced,completed,59,71,65
49,female,group D,some college,standard,completed,68,78,77
787,female,group D,some college,free/reduced,none,77,86,86

# Sort Index

In [10]:
# sort dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,male,group C,bachelor's degree,standard,completed,96,90,92
1,female,group D,some college,standard,completed,85,86,98
2,female,group B,master's degree,free/reduced,completed,52,70,62
3,female,group D,some high school,standard,none,59,72,80
4,female,group D,some college,free/reduced,none,69,65,74
...,...,...,...,...,...,...,...,...
995,female,group C,high school,free/reduced,completed,59,71,65
996,male,group C,master's degree,standard,completed,91,85,85
997,female,group B,some college,free/reduced,none,58,61,66
998,female,group E,some college,standard,none,87,85,93
999,female,group B,high school,standard,none,66,72,70

In [11]:
# sort descending by index
df_exams.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group B,high school,standard,none,66,72,70
998,female,group E,some college,standard,none,87,85,93
997,female,group B,some college,free/reduced,none,58,61,66
996,male,group C,master's degree,standard,completed,91,85,85
995,female,group C,high school,free/reduced,completed,59,71,65
...,...,...,...,...,...,...,...,...
4,female,group D,some college,free/reduced,none,69,65,74
3,female,group D,some high school,standard,none,59,72,80
2,female,group B,master's degree,free/reduced,completed,52,70,62
1,female,group D,some college,standard,completed,85,86,98
0,male,group C,bachelor's degree,standard,completed,96,90,92

In [ ]:
# sort descending by index
df_exams.sort_index(ascending=False, inplace=True)