In [1]:
import pandas as pd

# Read a .csv from a URL with Pandas
Target website: https://www.football-data.co.uk/data.php

### What is Web Scraping?
Web scraping is the process of automatically collecting data from websites using code.

Instead of copying data manually, you write a program to extract information from web pages.

In [4]:
# reading (extracting) 1 csv file from the website by read_csv method
df_premier25 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [6]:
# showing dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,E0,15/03/2026,14:00,Crystal Palace,Leeds,0,0,D,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.89,1.88,2.01,1.97
297,E0,15/03/2026,14:00,Man United,Aston Villa,3,1,H,0,0,...,1.90,1.95,NaN,NaN,1.93,1.96,1.88,1.90,1.96,2.02
298,E0,15/03/2026,14:00,Nott'm Forest,Fulham,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.91,1.92,1.85,2.04,1.93
299,E0,15/03/2026,16:30,Liverpool,Tottenham,1,1,D,1,0,...,1.80,2.00,NaN,NaN,1.85,2.05,1.77,1.96,1.88,2.11
300,E0,16/03/2026,20:00,Brentford,Wolves,2,2,D,2,1,...,1.88,1.98,NaN,NaN,1.95,1.98,1.89,1.89,1.93,2.05

In [7]:
# rename columns
df_premier25.rename(columns={'Date':'date','HomeTeam':'home_team',
                            'AwayTeam':'away_team', 'FTHG': 'home_goals',
                                'FTAG': 'away_goals'}, inplace=True)

In [9]:
# show dataframe
df_premier25

,Div,date,Time,home_team,away_team,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,E0,15/03/2026,14:00,Crystal Palace,Leeds,0,0,D,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.89,1.88,2.01,1.97
297,E0,15/03/2026,14:00,Man United,Aston Villa,3,1,H,0,0,...,1.90,1.95,NaN,NaN,1.93,1.96,1.88,1.90,1.96,2.02
298,E0,15/03/2026,14:00,Nott'm Forest,Fulham,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.91,1.92,1.85,2.04,1.93
299,E0,15/03/2026,16:30,Liverpool,Tottenham,1,1,D,1,0,...,1.80,2.00,NaN,NaN,1.85,2.05,1.77,1.96,1.88,2.11
300,E0,16/03/2026,20:00,Brentford,Wolves,2,2,D,2,1,...,1.88,1.98,NaN,NaN,1.95,1.98,1.89,1.89,1.93,2.05

# Read .csv from Multiple URLs with Pandas
https://www.football-data.co.uk/mmz4281/2526/E0.csv

Link: root + season + league

In [10]:
# link structure
"https://www.football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

In [13]:
# create a root variable (all the links have in common)
root = "https://www.football-data.co.uk/mmz4281/"
root

'https://www.football-data.co.uk/mmz4281/'

### Multiple leagues

* https://www.football-data.co.uk/mmz4281/2526/E0.csv
* https://www.football-data.co.uk/mmz4281/2526/E1.csv
* https://www.football-data.co.uk/mmz4281/2526/E2.csv
* https://www.football-data.co.uk/mmz4281/2526/E3.csv
* https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [14]:
# creating list of leagues
leagues = ['E0','E1', 'E2', 'E3', 'EC']

frames = []
# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + "2526" + "/"  + league + ".csv")
    frames.append(df)

In [15]:
# length of frames
len(frames)

5

In [17]:
# print(frames)

In [18]:
# show 1st element
frames[0].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08

In [20]:
# show last element
frames[4].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.9,1.9,1.92,1.93,1.90,1.9,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.0,1.8,2.05,1.82,2.02,1.8,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.0,1.8,2.14,1.72,2.03,1.8,1.96,1.75,2.06,1.84

### Multiple Seasons

In [22]:
for season in range(20,26):
    print(season)

20
21
22
23
24
25

In [24]:
for season in range(20,26):
    print(str(season) + str(season+1))

2021
2122
2223
2324
2425
2526

In [29]:
leagues = ['E0','E2', 'E3']

frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(20,26): # range of seasons
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv")
#         df['season'] = season   (add a season or a year column with the insert method) 
        df.insert(1, 'season', season) 
        # the first arg is the index where to put, then the name, value 
        frames.append(df)

In [30]:
# total frames (6 seasons x 3 leagues)
len(frames)

18

In [31]:
# show element
frames[0].head(3)

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04

In [33]:
# show the last element
frames[-1].head(3)

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,Unnamed: 132
0,E3,25,02/08/2025,15:00,Accrington,Gillingham,1,1,D,0,...,1.88,1.76,2.12,1.98,1.88,1.92,1.83,2.09,1.88,NaN
1,E3,25,02/08/2025,15:00,Barnet,Fleetwood Town,0,2,A,0,...,1.85,2.29,1.65,2.08,1.85,2.00,1.74,2.04,1.93,NaN
2,E3,25,02/08/2025,15:00,Bristol Rvs,Harrogate,0,1,A,0,...,2.03,1.85,2.00,1.85,2.03,1.78,1.96,1.88,2.12,NaN

# Organize All The Data in a Dictionary

In [34]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [35]:
# get a dictionary element
dict_countries['German Bundesliga']

'D1'

In [37]:
# dict data to store all the dataframe been extracted

dict_historical_data = {} 

# looping through key elements
for league in dict_countries:
    frames = [] # one dataframe per league
    for season in range(20,26):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league]+ ".csv")
        df.insert(1, 'season', season)
        frames.append(df)
    df_frames = pd.concat(frames) # storing all seasons of a league in a single dataframe
    dict_historical_data[league] = df_frames # assigning dataframe to a new dictionary

In [38]:
# show dataframe inside dict_historical_data
dict_historical_data['Spanish La Liga']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,20,12/09/2020,15:00,Eibar,Celta,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,20,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,20,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,20,13/09/2020,13:00,Alaves,Betis,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,20,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,SP1,25,15/03/2026,13:00,Mallorca,Espanol,2,1,H,0,...,3.05,2.50,3.0,3.10,NaN,NaN,NaN,NaN,NaN,NaN
276,SP1,25,15/03/2026,15:15,Barcelona,Sevilla,5,2,H,3,...,9.50,1.25,6.5,10.50,NaN,NaN,NaN,NaN,NaN,NaN
277,SP1,25,15/03/2026,17:30,Betis,Celta,1,1,D,0,...,3.70,2.00,3.3,3.90,NaN,NaN,NaN,NaN,NaN,NaN
278,SP1,25,15/03/2026,20:00,Sociedad,Osasuna,3,1,H,2,...,4.10,1.95,3.6,3.80,1.95,3.6,3.9,1.91,3.5,3.8
279,SP1,25,16/03/2026,20:00,Vallecano,Levante,1,1,D,0,...,4.90,1.85,3.5,4.33,NaN,NaN,NaN,NaN,NaN,NaN