In [16]:
import pandas as pd

In [17]:
df_laptops = pd.read_csv('laptop_price.csv', encoding="latin-1")

In [18]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

# Creating a Conditional Column from 2 Choices: np.where()

In [19]:
# we import numpy bexause where method belongs to numpy
import numpy as np

In [20]:
df_laptops['Price_euros']

0       1339.69
1        898.94
2        575.00
3       2537.45
4       1803.60
         ...
1298     638.00
1299    1499.00
1300     229.00
1301     764.00
1302     369.00
Name: Price_euros, Length: 1303, dtype: float64

In [21]:
df_laptops['Price_euros'] > 2000

0       False
1       False
2       False
3        True
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Name: Price_euros, Length: 1303, dtype: bool

In [22]:
# create an array based on price tiers
np.where(df_laptops['Price_euros'] > 2000, 'Expensive', 'Inexpensive') 
# the first arg is the condition, 
# the second arg is the value we wanna set if the condition is true
# the third arg is the value we wanna set if the condition is false

array(['Inexpensive', 'Inexpensive', 'Inexpensive', ..., 'Inexpensive',
       'Inexpensive', 'Inexpensive'], shape=(1303,), dtype='<U11')

In [23]:
# set it to a new column
df_laptops['Price_tier'] = np.where(df_laptops['Price_euros'] > 2000, 'Expensive', 'Inexpensive')

In [24]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Inexpensive
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Inexpensive
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Inexpensive
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Inexpensive

In [25]:
# count values in price_tier column
df_laptops.value_counts('Price_tier')

Price_tier
Inexpensive    1166
Expensive       137
Name: count, dtype: int64

# Exercise

In [ ]:
# create an array based in condition(screen size > 15)